### ISSUE TITLE
Internal FileNotFoundError during Icarus alignment

### ISSUE THREAD

**Issue by VictorTobiasson** [DSIMB/ICARUS#2]
Dear developers,

I am running the latest build of ICARUS on a HPC system (lsb_release:core-4.1-amd64:core-4.1-noarch) installed under a dedicated conda (23.9.0) environment (full config attached) as per instructions in the README.

I have recently attempted structural superimposistions with icarus of several polymerase sequences. Most pairs align well but several crash shortly after the Peel terminal output is given. All models are prediced using Alphafold2 and have well, to my inspection, formed .pdb file structures. Given the following command (sequences below);

python -u /home/tobiassonva/data/software/ICARUS/icarus.py -p1 EZ_46681.XP_001739203_ranked_0.pdb -p2 A3_AE009439_ranked_0.pdb -l 4 -c 16 --verbose --force

The program produces the following output, independent of -l or --force flags. Most but not all other alignments against the same reference are successful and I cant find any obvious correlation. I attached a .fasta (labeled csv for Githubs comfort) with such error causing sequences. 
[error_causing sequences.csv](https://github.com/user-attachments/files/15516594/error_causing.sequences.csv)
 
Best regards,
Victor 

-----------------
Clean input PDB files ... done

Peel EZ_46681.XP_001739203_ranked_0: 
    1384 aa
    Seq: MVICTIENLEFQCEIKKEINETKCEQFVYSFGHQEDGNTCCIIFCGWRPHLDIDLTELNKRINEPIGDVFIDLVETINEVINEQRHKEKQYRIIDHLEVIEGIPFVGYHTRKHIFGRIWLKNHKDINKVRKICNEMDIHIYEAHLSPDIMFMTDLGLRTMTFVHFNALISDQRKTKCKHEYYIDCKVLNLNEFASETKDKLRNGNLRVYWGTSPFINCEEGGTKTESFSENDKILIDKWITQMNSQRYNDNLFLDINRLQRLIEKYNLSPGRGIRETTQFQTQMMTQISQMNISKIFEKEIYDLNEETEVDGFNDEIEVTQELINKNEKLSNLQISENEKKEIIFKQSSEDDSKMECEEQDEVNGFGDLEMESDDSIKFQQNSNESIDSSERMEIEEVEVESKNSRLELLSQIPCTNIQIQRNNNKIFTQTLQNEGHIFLDENKSIEESIQQGNKTFQINLLDKSSRLVNKKVLFKGNETNPSDKLEINYKINENIIVFDTPPSLLEIKQEIKCHKINICHEGIIIPKINEIKELSYPIHCACTIPPPSFIDVVQSLTIQNNETEYIVNQEKKLNDPYSYFMISRINNPLISKKSCIICIQLLFHRIDESTGKYQNSKHDAIEGIVVYQSFRDKTLFYLIHTDLEAITYLHKTYKTLNTIDIICNNELSLIISLIKIINDEDADMIIAEDCSFTLQFINERYKLYKQGSFNDKINRLQNGKGVKGRLVLNIWHIYKECSKFSNYETDYIAKQVFNVSLPNVNYLCYNASEQLLSSFLRFHCCLLLLDYFDYINRIQEFAQFHACPLKGEIERGSQYKVECCLKRVSKNEFKLFSPSDNQLSSSRATDCVALVMEPQSGFHSNPVIVLDFLSMYPTTAIAYNICYSTCLGYVDDINIERKIGPMTYSFEKENLNTLKGNIHVVANGIMFVNACLRKGILPIMLEEMLSTRQHIKEIMKVFTKGTEEYKKCFLQQLALKLLCNVVYGYTGAGLSGRMPCNEIADAIVETARQTLEKAINFAERKFGGKVIYSDTDSLFVEMEGKTLEESFEVGKHLCEEFNKTIPPPMKLQLEKVYWPLVTVTKKRYFGMKYEKYETKPILEAKGLEAVRRDSCGVVRGMMSSVMNYLLNKDIEGMKQYLETNWEMIQKGEGFIDDFVISRPYRRHYAEGRQPPIGAKVILKERERDNTFYFQYGQRIKYVVVRTSSGKLCDSAVSPQFAASEQMVIDSDYYINKQINNSLQRILLPCGIDINKWYNTSLTRILFEGRKDKKIRIEDYYLIHKCIRCNKKIIGESYLCKACSYDKRVVIAEYQLHIKEIEQRLIDMKKRCLYCQLQYPFECVSTQCPISFKIIKEETEYRNFLKEVIKKNKTTMVNNYEIEQGVII
Peel A3_AE009439_ranked_0: 
    830 aa
    Seq: MLRTVWVDYARKGEPDVILVGRREDGNPAALVVKGFRPYFYAEVEDGFDPSEVERLSGVVEVEEVLLEHPYGGDRVELLRIVATYPKVVPKLREQVKKLDGVKEVYEADIPFVRRAAVDLNLPPASEVDVSDLDTGSWSGLPAYFADVEDARELDHRPYPIEDLVVASFDLEVLAEPGTTIKGASGPIIAISFAYSTPDGERRNYVITWKGEDESFEVDGVETEVIVCRSEAAALRRFFDEFRRVDPDVVFTYNGDEFDLPYLQHRAGKLGIDVSPLARPAGKRGIILKHGGGRYASDIFGRAHVDLYHTARKNLKLERFTLEEAVKDVLGVEKEEMELADINEAWKRGNLDELMRYSAEDAHYTLELGLELAQVELELSYLTRLPLPDATRFSFGQLAEWRAIYKARQEDILVPNKPTRDEYKRRRRKAYKGAIVFEPEIGLHENVVCVDFASLYPNVMVAHNISPDTFDCDCCPRVTVEEVDDPTDATVAPDVGHKFCKRRKGFFPRLVEGLIERRRELKRRLRKLDTESHPHEAKILDVRQQAYKVLANSYYGYMGWANARWFCRECAESVTAWGRYYISEVRRIAEEKYGLKVVYGDTDSLFVKLPDADLEETIERVKEFLKEVNGRLPVELELEDAYKRILFVTKKKYAGYTEDGKIVTKGLEVVRRDWAPIARETQRRVLKRILADNDPEAALKEIHEVLERLKSGDVDIDELAVTSQLTKKPSEYVQKGPHVRAALRLARHLGVEPEPGTIVRYVIVRGPGSVSDKAYPVELVREEGKEPDVDYYIEHQILPAVERIMRAIGYSRGQIVGETASQKTLDQFFG

Warning: jobs with proteins >200 residues and exploration level >= 4
	usually require a high amount of computational resources (RAM and disk memory).

User is bypassing the warning

Aligning EZ_46681.XP_001739203_ranked_0 against A3_AE009439_ranked_0Traceback (most recent call last):
  File "/home/tobiassonva/data/software/ICARUS/icarus.py", line 1551, in <module>
    main(p1, p2, exploration_level,
  File "/home/tobiassonva/data/software/ICARUS/icarus.py", line 210, in main
    single_kpax_tmscore = run_gdt(p1, p2, seed_alignment, opt_prune, ori_res_num_and_chain1, ori_res_num_and_chain2, keep_ori_resnum=True)
  File "/home/tobiassonva/data/software/ICARUS/icarus.py", line 104, in run_gdt
    ali = Alignment(query, target, opt_prune, seed_alignment, save_output, keep_ori_resnum)
  File "/vf/users/tobiassonva/data/software/ICARUS/src/alignment.py", line 74, in __init__
    self._get_match()
  File "/vf/users/tobiassonva/data/software/ICARUS/src/alignment.py", line 194, in _get_match
    target_pos, pu_pos, pu_seq, target_seq = self._get_all_matching_residues() 
  File "/vf/users/tobiassonva/data/software/ICARUS/src/alignment.py", line 162, in _get_all_matching_residues
    with open(f"{self.path}/{self.query.name}_{self.target.name}.wpairs", "r") as filin:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/KbrwP3CGQb/EZ_46681.XP_001739203_ranked_0-on-A3_AE009439_ranked_0/kpax_results/EZ_46681.XP_001739203_ranked_0_A3_AE009439_ranked_0.wpairs'
------------------
Conda environment:
[icarus_conda.csv](https://github.com/user-attachments/files/15516442/icarus_conda.csv)

**Comment by gabrielctn** [comment]
It looks like the KPAX `.wpairs` output file is not created in this example. Maybe there is an issue with KPAX specifically.
Would you mind sharing the two PDB files so that I can investigate further please ?
Thank you

**Comment by VictorTobiasson** [comment]
Here is a set of models for reference. The --p2 model is A3_AE009439_ranked_0 in all test cases. Models causing the errors are for example;

EZ_46681.XP_001739203_ranked_0
Mega_ERX633347.22.dc_ranked_0
Pokke_SRX327722.61
EA_5874.XP_954899_ranked_0

[models_subset.zip](https://github.com/user-attachments/files/15516957/models_subset.zip)

Thanks for the quick turnaround!

**Comment by gabrielctn** [comment]
Okay I think see the problem.
KPAX has issues with files which contain multiple "." in their filenames.
Every example you gave contains at least 2 dots in their filenames. Try simply renaming them in order to have only one "." and run again please.

**Comment by gabrielctn** [comment]
I should add a check at the beginning of the script

**Comment by VictorTobiasson** [comment]
Ah, silly but understandable. I will retry with altered names.

**Comment by gabrielctn** [comment]
Well, I agree and I think I had the issue once already during the development of ICARUS, but forgot to add a warning somewhere or simply rename the files for users in my script. I will add it so that users are at least warned and not blocked.
Unfortunately KPAX is not maintained anymore so cannot ask the developper to patch it.
